version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    depends_on:
      - postgres

volumes:
  postgres_data:
